const Search_RestsActionsConstants = {
    UPDATE_SEARCH_TYPE: 'UPDATE_SEARCH_TYPE',
    UPDATE_TAG_RESTATURANT: 'UPDATE_TAG_RESTATURANT',
    // LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    // LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    SEARCH_RESTAURANT: 'SEARCH_RESTAURANT',
    SEARCH_RESTAURANT_SUCCESS: 'SEARCH_RESTAURANT_SUCCESS',
    // SEARCH_RESTAURANT_FAILURE: 'SEARCH_RESTAURANT_FAILURE'
};

export { Search_RestsActionsConstants}
