const User_LoginActionsConstants = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT',
    PROFILE: 'PROFILE',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    SUCCESS_REGISTER: 'SUCCESS_REGISTER',
    SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
    FAIL_LOGIN: 'FAIL_LOGIN',
    FAIL_REGISTER: 'FAIL_REGISTER',
    FAIL_LOGOUT: 'FAIL_LOGOUT'
};

export { User_LoginActionsConstants}
