const Search_UsersActionsConstants = {
    UPDATE_SEARCH_TYPE_USER: 'UPDATE_SEARCH_TYPE_USER',
    UPDATE_TAG_USER: 'UPDATE_TAG_USER'
    // LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    // LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    // SEARCH_RESTAURANT: 'SEARCH_RESTAURANT',
    // SEARCH_RESTAURANT_SUCCESS: 'SEARCH_RESTAURANT_SUCCESS',
    // SEARCH_RESTAURANT_FAILURE: 'SEARCH_RESTAURANT_FAILURE'
};

export { Search_UsersActionsConstants}
